=== SimicAleksa/XML-project/Schemas/trademark/ZahtevZaPriznjanjeZiga.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="ZAHTEV_ZA_PRIZNANJE_ZIGA" xmlns="ZAHTEV_ZA_PRIZNANJE_ZIGA">

    <xs:element name="ZahtevZaPriznanjeZiga">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="PodnosilacPrijave" type="KTPersona" maxOccurs="unbounded"/>
                <xs:element name="Punomocnik" type="KTPersona"/>
                <xs:element name="ZajednickiPredstavnici" type="KTPersona" maxOccurs="1"
                    minOccurs="0"/>
                <xs:element name="Zig" type="KTZig"/>
                <xs:element name="BrojeviKlasaRobeIliUsluga">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="BrojKlaseRobeIliUsluge" maxOccurs="unbounded"
                                minOccurs="1" type="xs:int"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="PravoPrvenstvaIOsnov" type="xs:string"/>
                <xs:element name="Taksa" type="KTTaksa"/>
                <xs:element name="PriloziUzZahtev">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="PrimerakZnaka" type="xs:boolean"/>
                            <xs:element name="SpisakRobeIUsluga" type="xs:boolean"/>
                            <xs:element name="Punomocje" type="xs:boolean"/>
                            <xs:element name="PunomocjeRanijePrilozeno" type="xs:boolean"/>
                            <xs:element name="PunomocjeNaknadnoPrilozeno" type="xs:boolean"/>
                            <xs:element name="OpstiAktOZigu" type="xs:boolean"/>
                            <xs:element name="DokazPravaPrvenstva" type="xs:boolean"/>
                            <xs:element name="DokazUplateTakse" type="xs:boolean"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="DatumPodnosenja" type="xs:date"/>
            <xs:attribute name="BrojPrijave" type="xs:int"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="KTAdresa">
        <xs:sequence>
            <xs:element name="Ulica" type="xs:string"/>
            <xs:element name="BrojUlice" type="xs:int"/>
            <xs:element name="PostanskiBroj" type="xs:int"/>
            <xs:element name="MestoPrebivalista" type="xs:string"/>
            <xs:element name="DrzavaPrebivalista" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="KTKontaktInformacije">
        <xs:sequence>
            <xs:element name="Telefon" type="xs:string"/>
            <xs:element name="E-mail" type="xs:string"/>
            <xs:element name="Faks" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="KTPersona">
        <xs:sequence maxOccurs="1" minOccurs="1">
            <xs:element name="Ime" type="xs:string"/>
            <xs:element name="Prezime" type="xs:string"/>
            <xs:element name="Adresa" type="KTAdresa"/>
            <xs:element name="KontaktInformacije" type="KTKontaktInformacije"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="KTZig">
        <xs:sequence>
            <xs:element name="TipZiga" type="xs:string"/>
            <xs:element name="TipZnaka" type="xs:string"/>
            <xs:element name="IzgledZnaka" type="xs:base64Binary"/>
            <xs:element name="Boje">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" name="Boja" type="PTBoja"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="TransliteracijaZnaka" type="xs:string"/>
            <xs:element name="PrevodZnaka" type="xs:string"/>
            <xs:element name="OpisZnaka" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="PTBoja">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:complexType name="KTTaksa">
        <xs:sequence>
            <xs:element name="OsnovnaTaksa" type="xs:float"/>
            <xs:element name="TaksaZaBrojKlasa" type="xs:float"/>
            <xs:element name="TaksaZaGrafickoResenje" type="xs:float"/>
            <xs:element name="Ukupno" type="xs:float"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== SimicAleksa/XML-project/Schemas/ZAHTEV_ZA_PRIZNANJE_ZIGA.xml
<?xml version="1.0" encoding="UTF-8"?>
<ZahtevZaPriznanjeZiga xmlns="ZAHTEV_ZA_PRIZNANJE_ZIGA"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="ZAHTEV_ZA_PRIZNANJE_ZIGA file:/D:/FTN_stuff/xml%20i%20veb%20servisi/ZahtevZaPriznjanjeZiga.xsd">
    <PodnosilacPrijave>
        <Ime>Ime0</Ime>
        <Prezime>Prezime0</Prezime>
        <Adresa>
            <Ulica>Ulica0</Ulica>
            <BrojUlice>0</BrojUlice>
            <PostanskiBroj>0</PostanskiBroj>
            <MestoPrebivalista>MestoPrebivalista0</MestoPrebivalista>
            <DrzavaPrebivalista>DrzavaPrebivalista0</DrzavaPrebivalista>
        </Adresa>
        <KontaktInformacije>
            <Telefon>Telefon0</Telefon>
            <E-mail>E-mail0</E-mail>
            <Faks>Faks0</Faks>
        </KontaktInformacije>
    </PodnosilacPrijave>
    <Punomocnik>
        <Ime>Ime1</Ime>
        <Prezime>Prezime1</Prezime>
        <Adresa>
            <Ulica>Ulica1</Ulica>
            <BrojUlice>0</BrojUlice>
            <PostanskiBroj>0</PostanskiBroj>
            <MestoPrebivalista>MestoPrebivalista1</MestoPrebivalista>
            <DrzavaPrebivalista>DrzavaPrebivalista1</DrzavaPrebivalista>
        </Adresa>
        <KontaktInformacije>
            <Telefon>Telefon1</Telefon>
            <E-mail>E-mail1</E-mail>
            <Faks>Faks1</Faks>
        </KontaktInformacije>
    </Punomocnik>
    <ZajednickiPredstavnici>
        <Ime>Ime2</Ime>
        <Prezime>Prezime2</Prezime>
        <Adresa>
            <Ulica>Ulica2</Ulica>
            <BrojUlice>0</BrojUlice>
            <PostanskiBroj>0</PostanskiBroj>
            <MestoPrebivalista>MestoPrebivalista2</MestoPrebivalista>
            <DrzavaPrebivalista>DrzavaPrebivalista2</DrzavaPrebivalista>
        </Adresa>
        <KontaktInformacije>
            <Telefon>Telefon2</Telefon>
            <E-mail>E-mail2</E-mail>
            <Faks>Faks2</Faks>
        </KontaktInformacije>
    </ZajednickiPredstavnici>
    <Zig>
        <TipZiga>TipZiga0</TipZiga>
        <TipZnaka>TipZnaka0</TipZnaka>
        <IzgledZnaka>ZGVmYXVsdA==</IzgledZnaka>
        <Boje>
            <Boja>Boja0</Boja>
            <Boja>Boja1</Boja>
        </Boje>
        <TransliteracijaZnaka>TransliteracijaZnaka0</TransliteracijaZnaka>
        <PrevodZnaka>PrevodZnaka0</PrevodZnaka>
        <OpisZnaka>OpisZnaka0</OpisZnaka>
    </Zig>
    <BrojeviKlasaRobeIliUsluga>
        <BrojKlaseRobeIliUsluge>
        </BrojKlaseRobeIliUsluge>
    </BrojeviKlasaRobeIliUsluga>
    <PravoPrvenstvaIOsnov>PravoPrvenstvaIOsnov0</PravoPrvenstvaIOsnov>
    <Taksa>
        <OsnovnaTaksa>0</OsnovnaTaksa>
        <TaksaZaNestoKlasa>0</TaksaZaNestoKlasa>
        <TaksaZaGrafickoResenje>0</TaksaZaGrafickoResenje>
        <Ukupno>0</Ukupno>
    </Taksa>
    <PotpisIPecatPodnosioca>ZGVmYXVsdA==</PotpisIPecatPodnosioca>
    <PriloziUzZahtev>
        <PrimerakZnaka>false</PrimerakZnaka>
        <SpisakRobeIUsluga>false</SpisakRobeIUsluga>
        <Punomocje>false</Punomocje>
        <PunomocjeRanijePrilozeno>false</PunomocjeRanijePrilozeno>
        <PunomocjeNaknadnoPrilozeno>false</PunomocjeNaknadnoPrilozeno>
        <OpstiAktOZigu>false</OpstiAktOZigu>
        <DokazPravaPrvenstva>false</DokazPravaPrvenstva>
        <DokazUplateTakse>false</DokazUplateTakse>
    </PriloziUzZahtev>
</ZahtevZaPriznanjeZiga>
