=== SimicAleksa/XML-project/XML_WS_Trademark_backend/src/main/resources/xmls/ZahtevZaPriznjanjeZiga.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="ZAHTEV_ZA_PRIZNANJE_ZIGA" xmlns="ZAHTEV_ZA_PRIZNANJE_ZIGA">

    <xs:element name="ZahtevZaPriznanjeZiga">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="MetaData">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="BrojPrijave" type="xs:string"/>
                            <xs:element name="DatumPodnosenja" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="PodnosilacPrijave" type="KTPersona" maxOccurs="unbounded"/>
                <xs:element name="Punomocnik" type="KTPersona"/>
                <xs:element name="ZajednickiPredstavnici" type="KTPersona" maxOccurs="1"
                    minOccurs="0"/>
                <xs:element name="Zig" type="KTZig"/>
                <xs:element name="BrojeviKlasaRobeIliUsluga">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="BrojKlaseRobeIliUsluge" maxOccurs="unbounded"
                                minOccurs="1" type="xs:int"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="PravoPrvenstvaIOsnov" type="xs:string"/>
                <xs:element name="Taksa" type="KTTaksa"/>
                <xs:element name="PriloziUzZahtev">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="PrimerakZnaka" type="xs:boolean"/>
                            <xs:element name="SpisakRobeIUsluga" type="xs:boolean"/>
                            <xs:element name="Punomocje" type="xs:boolean"/>
                            <xs:element name="PunomocjeRanijePrilozeno" type="xs:boolean"/>
                            <xs:element name="PunomocjeNaknadnoPrilozeno" type="xs:boolean"/>
                            <xs:element name="OpstiAktOZigu" type="xs:boolean"/>
                            <xs:element name="DokazPravaPrvenstva" type="xs:boolean"/>
                            <xs:element name="DokazUplateTakse" type="xs:boolean"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:int"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="KTAdresa">
        <xs:sequence>
            <xs:element name="Ulica">
                <xs:simpleType>
                    <xs:restriction base="xs:string"> </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="BrojUlice">
                <xs:simpleType>
                    <xs:restriction base="xs:int"> </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="PostanskiBroj">
                <xs:simpleType>
                    <xs:restriction base="xs:int"> </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="MestoPrebivalista">
                <xs:simpleType>
                    <xs:restriction base="xs:string"> </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="DrzavaPrebivalista">
                <xs:simpleType>
                    <xs:restriction base="xs:string"> </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="KTKontaktInformacije">
        <xs:sequence>
            <xs:element name="Telefon">
                <xs:simpleType>
                    <xs:restriction base="xs:string"> </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="E-mail">
                <xs:simpleType>
                    <xs:restriction base="xs:string"> </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Faks">
                <xs:simpleType>
                    <xs:restriction base="xs:string"> </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="KTPersona">
        <xs:sequence maxOccurs="1" minOccurs="1">
            <xs:element name="Ime">
                <xs:simpleType>
                    <xs:restriction base="xs:string"> </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Adresa" type="KTAdresa"/>
            <xs:element name="KontaktInformacije" type="KTKontaktInformacije"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="KTZig">
        <xs:sequence>
            <xs:element name="TipZiga" type="xs:string"/>
            <xs:element name="TipZnaka" type="xs:string"/>
            <xs:element name="IzgledZnaka" type="xs:base64Binary"/>
            <xs:element name="Boje" type="xs:string"> </xs:element>
            <xs:element name="TransliteracijaZnaka" type="xs:string"/>
            <xs:element name="PrevodZnaka" type="xs:string"/>
            <xs:element name="OpisZnaka" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="KTTaksa">
        <xs:sequence>
            <xs:element name="OsnovnaTaksa" type="xs:float"/>
            <xs:element name="TaksaZaBrojKlasa" type="xs:float"/>
            <xs:element name="TaksaZaGrafickoResenje" type="xs:float"/>
            <xs:element name="Ukupno" type="xs:float"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== SimicAleksa/XML-project/XML_WS_Trademark_backend/src/main/resources/xmls/ZahtevZaPriznjanjeZiga.xml
<?xml version="1.0" encoding="UTF-8"?>
<ZahtevZaPriznanjeZiga xmlns="ZAHTEV_ZA_PRIZNANJE_ZIGA"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="ZAHTEV_ZA_PRIZNANJE_ZIGA file:/D:/Projects/web/XML-project/XML_WS_Trademark_backend/src/main/resources/xmls/ZahtevZaPriznjanjeZiga.xsd" id="0">
    <MetaData>
        <BrojPrijave>BrojPrijave0</BrojPrijave>
        <DatumPodnosenja>2006-05-04</DatumPodnosenja>
    </MetaData>
    <PodnosilacPrijave>
        <Ime>Ime0</Ime>
        <Adresa>
            <Ulica>Ulica0</Ulica>
            <BrojUlice>0</BrojUlice>
            <PostanskiBroj>0</PostanskiBroj>
            <MestoPrebivalista>MestoPrebivalista0</MestoPrebivalista>
            <DrzavaPrebivalista>DrzavaPrebivalista0</DrzavaPrebivalista>
        </Adresa>
        <KontaktInformacije>
            <Telefon>Telefon0</Telefon>
            <E-mail>E-mail0</E-mail>
            <Faks>Faks0</Faks>
        </KontaktInformacije>
    </PodnosilacPrijave>
    <PodnosilacPrijave>
        <Ime>Ime1</Ime>
        <Adresa>
            <Ulica>Ulica1</Ulica>
            <BrojUlice>0</BrojUlice>
            <PostanskiBroj>0</PostanskiBroj>
            <MestoPrebivalista>MestoPrebivalista1</MestoPrebivalista>
            <DrzavaPrebivalista>DrzavaPrebivalista1</DrzavaPrebivalista>
        </Adresa>
        <KontaktInformacije>
            <Telefon>Telefon1</Telefon>
            <E-mail>E-mail1</E-mail>
            <Faks>Faks1</Faks>
        </KontaktInformacije>
    </PodnosilacPrijave>
    <Punomocnik>
        <Ime>Ime2</Ime>
        <Adresa>
            <Ulica>Ulica2</Ulica>
            <BrojUlice>0</BrojUlice>
            <PostanskiBroj>0</PostanskiBroj>
            <MestoPrebivalista>MestoPrebivalista2</MestoPrebivalista>
            <DrzavaPrebivalista>DrzavaPrebivalista2</DrzavaPrebivalista>
        </Adresa>
        <KontaktInformacije>
            <Telefon>Telefon2</Telefon>
            <E-mail>E-mail2</E-mail>
            <Faks>Faks2</Faks>
        </KontaktInformacije>
    </Punomocnik>
    <ZajednickiPredstavnici>
        <Ime>Ime3</Ime>
        <Adresa>
            <Ulica>Ulica3</Ulica>
            <BrojUlice>0</BrojUlice>
            <PostanskiBroj>0</PostanskiBroj>
            <MestoPrebivalista>MestoPrebivalista3</MestoPrebivalista>
            <DrzavaPrebivalista>DrzavaPrebivalista3</DrzavaPrebivalista>
        </Adresa>
        <KontaktInformacije>
            <Telefon>Telefon3</Telefon>
            <E-mail>E-mail3</E-mail>
            <Faks>Faks3</Faks>
        </KontaktInformacije>
    </ZajednickiPredstavnici>
    <Zig>
        <TipZiga>TipZiga0</TipZiga>
        <TipZnaka>TipZnaka0</TipZnaka>
        <IzgledZnaka>ZGVmYXVsdA==</IzgledZnaka>
        <Boje>Boje0</Boje>
        <TransliteracijaZnaka>TransliteracijaZnaka0</TransliteracijaZnaka>
        <PrevodZnaka>PrevodZnaka0</PrevodZnaka>
        <OpisZnaka>OpisZnaka0</OpisZnaka>
    </Zig>
    <BrojeviKlasaRobeIliUsluga>
        <BrojKlaseRobeIliUsluge>0</BrojKlaseRobeIliUsluge>
        <BrojKlaseRobeIliUsluge>0</BrojKlaseRobeIliUsluge>
    </BrojeviKlasaRobeIliUsluga>
    <PravoPrvenstvaIOsnov>PravoPrvenstvaIOsnov0</PravoPrvenstvaIOsnov>
    <Taksa>
        <OsnovnaTaksa>0</OsnovnaTaksa>
        <TaksaZaBrojKlasa>0</TaksaZaBrojKlasa>
        <TaksaZaGrafickoResenje>0</TaksaZaGrafickoResenje>
        <Ukupno>0</Ukupno>
    </Taksa>
    <PriloziUzZahtev>
        <PrimerakZnaka>false</PrimerakZnaka>
        <SpisakRobeIUsluga>false</SpisakRobeIUsluga>
        <Punomocje>false</Punomocje>
        <PunomocjeRanijePrilozeno>false</PunomocjeRanijePrilozeno>
        <PunomocjeNaknadnoPrilozeno>false</PunomocjeNaknadnoPrilozeno>
        <OpstiAktOZigu>false</OpstiAktOZigu>
        <DokazPravaPrvenstva>false</DokazPravaPrvenstva>
        <DokazUplateTakse>false</DokazUplateTakse>
    </PriloziUzZahtev>
</ZahtevZaPriznanjeZiga>

=== SimicAleksa/XML-project/XML_WS_Trademark_backend/src/main/resources/formats_data/ZahtevZaPriznanjeZiga.xml
<?xml version="1.0" encoding="UTF-8"?>
<z:ZahtevZaPriznanjeZiga xmlns="ZAHTEV_ZA_PRIZNANJE_ZIGA"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns:z="ZAHTEV_ZA_PRIZNANJE_ZIGA"
 xsi:schemaLocation="ZAHTEV_ZA_PRIZNANJE_ZIGA file:/D:/Projects/web/XML-project/XML_WS_Trademark_backend/src/main/resources/xmls/ZahtevZaPriznjanjeZiga.xsd" id="0">
    <z:MetaData>
        <z:BrojPrijave>BrojPrijave0</z:BrojPrijave>
        <z:DatumPodnosenja>2006-05-04</z:DatumPodnosenja>
    </z:MetaData>
    <z:PodnosilacPrijave>
        <z:Ime>Ime0</z:Ime>
        <z:Adresa>
            <z:Ulica>Ulica0</z:Ulica>
            <z:BrojUlice>0</z:BrojUlice>
            <z:PostanskiBroj>0</z:PostanskiBroj>
            <z:MestoPrebivalista>MestoPrebivalista0</z:MestoPrebivalista>
            <z:DrzavaPrebivalista>DrzavaPrebivalista0</z:DrzavaPrebivalista>
        </z:Adresa>
        <z:KontaktInformacije>
            <z:Telefon>Telefon0</z:Telefon>
            <z:E-mail>E-mail0</z:E-mail>
            <z:Faks>Faks0</z:Faks>
        </z:KontaktInformacije>
    </z:PodnosilacPrijave>
    <z:PodnosilacPrijave>
        <z:Ime>Ime1</z:Ime>
        <z:Adresa>
            <z:Ulica>Ulica1</z:Ulica>
            <z:BrojUlice>0</z:BrojUlice>
            <z:PostanskiBroj>0</z:PostanskiBroj>
            <z:MestoPrebivalista>MestoPrebivalista1</z:MestoPrebivalista>
            <z:DrzavaPrebivalista>DrzavaPrebivalista1</z:DrzavaPrebivalista>
        </z:Adresa>
        <z:KontaktInformacije>
            <z:Telefon>Telefon1</z:Telefon>
            <z:E-mail>E-mail1</z:E-mail>
            <z:Faks>Faks1</z:Faks>
        </z:KontaktInformacije>
    </z:PodnosilacPrijave>
    <z:Punomocnik>
        <z:Ime>Ime2</z:Ime>
        <z:Adresa>
            <z:Ulica>Ulica2</z:Ulica>
            <z:BrojUlice>0</z:BrojUlice>
            <z:PostanskiBroj>0</z:PostanskiBroj>
            <z:MestoPrebivalista>MestoPrebivalista2</z:MestoPrebivalista>
            <z:DrzavaPrebivalista>DrzavaPrebivalista2</z:DrzavaPrebivalista>
        </z:Adresa>
        <z:KontaktInformacije>
            <z:Telefon>Telefon2</z:Telefon>
            <z:E-mail>E-mail2</z:E-mail>
            <z:Faks>Faks2</z:Faks>
        </z:KontaktInformacije>
    </z:Punomocnik>
    <z:ZajednickiPredstavnici>
        <z:Ime>Ime3</z:Ime>
        <z:Adresa>
            <z:Ulica>Ulica3</z:Ulica>
            <z:BrojUlice>0</z:BrojUlice>
            <z:PostanskiBroj>0</z:PostanskiBroj>
            <z:MestoPrebivalista>MestoPrebivalista3</z:MestoPrebivalista>
            <z:DrzavaPrebivalista>DrzavaPrebivalista3</z:DrzavaPrebivalista>
        </z:Adresa>
        <z:KontaktInformacije>
            <z:Telefon>Telefon3</z:Telefon>
            <z:E-mail>E-mail3</z:E-mail>
            <z:Faks>Faks3</z:Faks>
        </z:KontaktInformacije>
    </z:ZajednickiPredstavnici>
    <z:Zig>
        <z:TipZiga>TipZiga0</z:TipZiga>
        <z:TipZnaka>TipZnaka0</z:TipZnaka>
        <z:IzgledZnaka>ZGVmYXVsdA==</z:IzgledZnaka>
        <z:Boje>Boje0</z:Boje>
        <z:TransliteracijaZnaka>TransliteracijaZnaka0</z:TransliteracijaZnaka>
        <z:PrevodZnaka>PrevodZnaka0</z:PrevodZnaka>
        <z:OpisZnaka>OpisZnaka0</z:OpisZnaka>
    </z:Zig>
    <z:BrojeviKlasaRobeIliUsluga>
        <z:BrojKlaseRobeIliUsluge>0</z:BrojKlaseRobeIliUsluge>
        <z:BrojKlaseRobeIliUsluge>0</z:BrojKlaseRobeIliUsluge>
    </z:BrojeviKlasaRobeIliUsluga>
    <z:PravoPrvenstvaIOsnov>PravoPrvenstvaIOsnov0</z:PravoPrvenstvaIOsnov>
    <z:Taksa>
        <z:OsnovnaTaksa>0</z:OsnovnaTaksa>
        <z:TaksaZaBrojKlasa>0</z:TaksaZaBrojKlasa>
        <z:TaksaZaGrafickoResenje>0</z:TaksaZaGrafickoResenje>
        <z:Ukupno>0</z:Ukupno>
    </z:Taksa>
    <z:PriloziUzZahtev>
        <z:PrimerakZnaka>false</z:PrimerakZnaka>
        <z:SpisakRobeIUsluga>false</z:SpisakRobeIUsluga>
        <z:Punomocje>false</z:Punomocje>
        <z:PunomocjeRanijePrilozeno>false</z:PunomocjeRanijePrilozeno>
        <z:PunomocjeNaknadnoPrilozeno>false</z:PunomocjeNaknadnoPrilozeno>
        <z:OpstiAktOZigu>false</z:OpstiAktOZigu>
        <z:DokazPravaPrvenstva>false</z:DokazPravaPrvenstva>
        <z:DokazUplateTakse>false</z:DokazUplateTakse>
    </z:PriloziUzZahtev>
</z:ZahtevZaPriznanjeZiga>
